### PR TITLE
Update module.json

### PR DESCRIPTION
**Pull request by colneck**
Added values for recieved OSC data: active/pending cuenumber, -list, -text.

### CODE REVIEW

**Comment by benkuper** [comment]
please bump the version so people already having the module can update

**Comment by colneck** [comment]
Bumped the version in patch-2. Do I have to create a new PR?

**Comment by benkuper** [comment]
all good, next time you can just push on the same branch, PR will update itself so by the time I merge it, all commits will be integrated instead of creating different ones

**Comment by colneck** [comment]
Ah, alright.. but I think you already merged them and closed the PR, before I changed the version number. Anyway: thanks!! :)Am 18.10.2024 um 19:16 schrieb Ben Kuper ***@***.***>:﻿
all good, next time you can just push on the same branch, PR will update itself so by the time I merge it, all commits will be integrated instead of creating different ones

**Pull request merged**
